language: ruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby
  - rbx-2

script:
  - gem install bundler -v '> 2'
  - bundle exec rubocop
  - bundle exec rspec spec

# safelist
branches:
  only:
  - master
